all: determinant3x3 kofakhesap2x2 satsutsec

determinant3x3.out: determinant3x3.c
	gcc determinant3x3.c -o determinant3x3.out

kofakhesap2x2.out: kofakhesap2x2.c
	gcc kofakhesap2x2.c -o kofakhesap2x2.out
	
satsutsec.out: satsutsec.c
	gcc satsutsec.c -o satsutsec.out
